[toolchain]
channel = "1.84.1"
components = ["rustfmt", "rustc", "cargo"]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "x86_64-pc-windows-gnu",
  "aarch64-apple-darwin",
]
profile = "minimal"
